name: Update metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.PAT }}
          user: 0xsysr3ll
          base_indepth: yes
          base_hireable: yes
          config_timezone: Europe/Paris
          repositories_affiliations: owner, collaborator, organization_member
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_notable: yes
          plugin_achievements: yes